use_frameworks!

target 'social-interact_Example' do
  pod 'social-interact', :path => '../'

  target 'social-interact_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
  end
end
